#!/bin/sh
set -e
apt-key adv --keyserver pgp.mit.edu --recv-key 799058698E65316A2E7A4FF42EAE1437F7D2C623
echo "deb http://repos.zend.com/zend-server/$@/deb_apache2.4 server non-free" >> /etc/apt/sources.list.d/zend-server.list
exit 0